services:
  - type: web
    name: odiobot
    runtime: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: BOT_TOKEN
        value: # (vacío aquí; ya la tienes definida en Render → Environment)
